name: Run Unit Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Test
        run: |
          sudo apt-get update
          sudo apt-get install libgtest-dev
          sudo apt-get install cmake # install CMake for building Google Test
          cd /usr/src/googletest
          sudo cmake CMakeLists.txt
          sudo make
          sudo cp *.a /usr/lib

      - name: Compile and Run Tests
        run: |
          g++ -o FizzBuzz FizzBuzz.cpp FizzBuzz.tests.cpp -lgtest -lgtest_main -pthread
          ./FizzBuzz
