name: Run Unit Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile and Run Tests
        run: |
          g++ -o FizzBuzz FizzBuzz.cpp FizzBuzz.tests.cpp
          ./FizzBuzz
