name: CI

on:
  push:
    branches:
      - master  # Adjust this branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest  # Use the desired runner platform

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up C++ environment
      run: |
        sudo apt-get update
        sudo apt-get install -y g++
        sudo apt-get install -y cmake
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo find /usr/src/gtest -name '*.a' -exec mv {} /usr/lib/ \;
      env:
        GTEST_ROOT: /usr/src/gtest

    - name: Build and run tests
      run: |
        g++ -o FizzBuzzTests FizzBuzz.tests.cpp -lgtest -lgtest_main -pthread
        ./FizzBuzzTests
