name: Run Unit Tests

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up CMake
        uses: lukka/run-cmake@v1
        with:
          cmakeListsOrSettingsJsonPath: . # Adjust this path if necessary

      - name: Build and Run Tests
        run: |
          cmake --build . --config Release
          ctest --output-on-failure
